# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6803036d9ba2b9c3993660afc6758696edbc556fd7e2350f06d92d4db54d4c3be4911da8e006108b13a2ea023a6d0c165d4e7cace7f2c98b21b1b0366e36b60f

test:
  secret_key_base: f2b9037377ded9fd3ed7c3d8d26d4728b1135bca74fbdcadf093739a6cd53ccc1689d94be7aa6af1520fb29508a18e63efe139e37c4a89574b8ed69377f64f5b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
